### ISSUE TITLE
Downgraded of Setfields, change in compat?

### ISSUE THREAD

**Issue by luboshanus** [baggepinnen/Hyperopt.jl#92] opened 2022-11-25 15:07 UTC
Hi,

why adding `Hyperopt` downgrades `Setfields`

```julia
[efcf1570] ↓ Setfield v1.1.1 ⇒ v0.8.2
```

Does the `Project.toml` make it? I don't know, but don't think so.
```
Setfield = "0.7, 0.8, 1.0"
```

**Comment by baggepinnen** [comment] 2022-11-25 15:25
It might be one of the other dependencies of Hyperopt that has stale compat requirements

**Comment by baggepinnen** [comment] 2022-11-25 15:28
You can try to `pkg> add Setfield@1.1.1` to get the package manager to tell you which package causes the conflict

**Comment by luboshanus** [comment] 2022-11-25 15:45
Ok, here is the output after `add Setfield@1.1.1`

```julia
(@v1.6) pkg> add Setfield@1.1.1
   Resolving package versions...
   Installed NLopt_jll ────────────── v2.7.1+0
   Installed CodecBzip2 ───────────── v0.7.2
   Installed SpecialFunctions ─────── v1.8.7
   Installed FastGaussQuadrature ──── v0.4.9
   Installed Hyperopt ─────────────── v0.4.4
   Installed MutableArithmetics ───── v1.1.0
   Installed LineSearches ─────────── v7.2.0
   Installed ThreadPools ──────────── v1.2.1
   Installed Distances ────────────── v0.10.7
   Installed ArrayInterfaceCore ───── v0.1.26
   Installed FiniteDiff ───────────── v2.17.0
   Installed NLopt ────────────────── v0.6.5
   Installed PDMats ───────────────── v0.10.1
   Installed MathProgBase ─────────── v0.7.8
   Installed StatsFuns ────────────── v0.9.18
   Installed Juno ─────────────────── v0.8.4
   Installed ElasticPDMats ────────── v0.2.2
   Installed BenchmarkTools ───────── v1.3.2
   Installed ScikitLearnBase ──────── v0.5.0
   Installed Parameters ───────────── v0.12.3
   Installed Media ────────────────── v0.5.0
   Installed ElasticArrays ────────── v1.2.10
   Installed NLSolversBase ────────── v7.8.3
   Installed PositiveFactorizations ─ v0.2.4
   Installed BayesianOptimization ─── v0.2.5
   Installed GaussianProcesses ────── v0.12.5
   Installed Sobol ────────────────── v1.5.0
   Installed Optim ────────────────── v1.7.4
   Installed MathOptInterface ─────── v1.10.0
  Downloaded artifact: NLopt
    Updating `~/.julia/environments/v1.6/Project.toml`
  [93e5fe13] ↓ Hyperopt v0.5.5 ⇒ v0.4.4
  [efcf1570] + Setfield v1.1.1
    Updating `~/.julia/environments/v1.6/Manifest.toml`
  [30b0a656] + ArrayInterfaceCore v0.1.26
  [4c6ed407] + BayesianOptimization v0.2.5
  [6e4b80f9] + BenchmarkTools v1.3.2
  [49dc2e85] - Calculus v0.5.1
  [523fee87] + CodecBzip2 v0.7.2
  [b4f34e82] + Distances v0.10.7
  [fa6b7ba4] - DualNumbers v0.6.8
  [fdbdab4c] + ElasticArrays v1.2.10
  [2904ab23] + ElasticPDMats v0.2.2
  [442a2c76] + FastGaussQuadrature v0.4.9
  [6a86dc24] + FiniteDiff v2.17.0
  [891a1506] + GaussianProcesses v0.12.5
  [34004b35] - HypergeometricFunctions v0.3.11
  [93e5fe13] ↓ Hyperopt v0.5.5 ⇒ v0.4.4
  [e5e0dc1b] + Juno v0.8.4
  [d3d80556] + LineSearches v7.2.0
  [b8f27783] + MathOptInterface v1.10.0
  [fdba3010] + MathProgBase v0.7.8
  [e89f7d12] + Media v0.5.0
  [77543b7f] - MultiKDE v0.1.1
  [d8a4904e] + MutableArithmetics v1.1.0
  [d41bc354] + NLSolversBase v7.8.3
  [76087f3c] + NLopt v0.6.5
  [429524aa] + Optim v1.7.4
  [90014a1f] ↓ PDMats v0.11.16 ⇒ v0.10.1
  [d96e819e] + Parameters v0.12.3
  [85a6dd25] + PositiveFactorizations v0.2.4
  [6e75b9c4] + ScikitLearnBase v0.5.0
  [efcf1570] ↑ Setfield v0.8.2 ⇒ v1.1.1
  [ed01d8cd] + Sobol v1.5.0
  [276daf66] ↓ SpecialFunctions v2.1.7 ⇒ v1.8.7
  [4c63d2b9] ↓ StatsFuns v1.0.1 ⇒ v0.9.18
  [b189fb0b] ↓ ThreadPools v2.1.1 ⇒ v1.2.1
  [079eb43e] + NLopt_jll v2.7.1+0
  [9abbd945] + Profile
```

**Comment by baggepinnen** [comment] 2022-11-25 15:48
ok, that only downgraded hyperopt :P What if you do `pkg> add Hyperopt@0.5.5 Setfield@1.1.1` in one go?

**Comment by luboshanus** [comment] 2022-11-25 15:55
haha :)

```julia
(@v1.6) pkg> add Hyperopt@0.5.5 Setfield@1.1.1
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Hyperopt [93e5fe13]:
 Hyperopt [93e5fe13] log:
 ├─possible versions are: 0.1.0-0.5.5 or uninstalled
 ├─restricted to versions 0.5.5 by an explicit requirement, leaving only versions 0.5.5
 └─restricted by compatibility requirements with Setfield [efcf1570] to versions: 0.1.0-0.4.4 or uninstalled — no versions left
   └─Setfield [efcf1570] log:
     ├─possible versions are: 0.2.0-1.1.1 or uninstalled
     └─restricted to versions 1.1.1 by an explicit requirement, leaving only versions 1.1.1
```

**Comment by baggepinnen** [comment] 2022-11-25 15:59
That's really strange, for some reason the general registry has a different compat bounds for Setfield than what is specified in the Project.toml file in this repo. I'll try to make a new release and see if that fixes it

**Comment by baggepinnen** [comment] 2022-11-25 17:07
I made a new release as well, I hope the problem is fixed now!

**Closed** 2022-11-25 17:06 UTC
